
const students = [
    {"Naam":"Evelyn","Opdracht":"SCRUM","Moeilijk":3,"Leuk":4,"Id":1,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D1-1","Moeilijk":3,"Leuk":3,"Id":2,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D2-1","Moeilijk":1,"Leuk":3,"Id":3,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":4,"Id":4,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D2-3","Moeilijk":2,"Leuk":3,"Id":5,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D2-4","Moeilijk":3,"Leuk":4,"Id":6,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D2-5","Moeilijk":3,"Leuk":4,"Id":7,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D3-1","Moeilijk":3,"Leuk":4,"Id":8,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D3-2","Moeilijk":3,"Leuk":4,"Id":9,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D3-4","Moeilijk":4,"Leuk":4,"Id":10,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D3-5","Moeilijk":4,"Leuk":4,"Id":11,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":5,"Leuk":5,"Id":12,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D4-1","Moeilijk":4,"Leuk":5,"Id":13,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":3,"Leuk":4,"Id":14,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W1D5 - Project - Galgje","Moeilijk":3,"Leuk":3,"Id":15,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D1-1","Moeilijk":1,"Leuk":5,"Id":16,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D1-2","Moeilijk":2,"Leuk":5,"Id":17,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D2-1","Moeilijk":3,"Leuk":4,"Id":18,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D2-2","Moeilijk":3,"Leuk":4,"Id":19,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D2-3","Moeilijk":3,"Leuk":4,"Id":20,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D3-1","Moeilijk":4,"Leuk":4,"Id":21,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D3-2","Moeilijk":1,"Leuk":3,"Id":22,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D3-3","Moeilijk":4,"Leuk":4,"Id":23,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":3,"Id":24,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D4-2","Moeilijk":4,"Leuk":4,"Id":25,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D4-3","Moeilijk":1,"Leuk":3,"Id":26,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":3,"Leuk":4,"Id":27,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D1-1","Moeilijk":3,"Leuk":4,"Id":28,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D1-2","Moeilijk":2,"Leuk":4,"Id":29,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D1-3","Moeilijk":3,"Leuk":4,"Id":30,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D1-4","Moeilijk":3,"Leuk":3,"Id":31,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D2-1","Moeilijk":2,"Leuk":4,"Id":32,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D2-2","Moeilijk":3,"Leuk":3,"Id":33,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D2-3","Moeilijk":3,"Leuk":5,"Id":34,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D3-1","Moeilijk":4,"Leuk":4,"Id":35,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D3-2","Moeilijk":4,"Leuk":5,"Id":36,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D3-3","Moeilijk":3,"Leuk":5,"Id":37,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D3-4","Moeilijk":4,"Leuk":5,"Id":38,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D4-1","Moeilijk":5,"Leuk":5,"Id":39,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D4-2","Moeilijk":1,"Leuk":5,"Id":40,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":2,"Leuk":5,"Id":41,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D2-1","Moeilijk":1,"Leuk":5,"Id":42,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D2-2","Moeilijk":1,"Leuk":5,"Id":43,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D2-3","Moeilijk":1,"Leuk":5,"Id":44,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D2-4","Moeilijk":1,"Leuk":5,"Id":45,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3-1","Moeilijk":1,"Leuk":5,"Id":46,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":5,"Id":47,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3-3","Moeilijk":1,"Leuk":5,"Id":48,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3-4","Moeilijk":1,"Leuk":5,"Id":49,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3-5","Moeilijk":1,"Leuk":5,"Id":50,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":1,"Leuk":5,"Id":51,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W5D4-1","Moeilijk":3,"Leuk":4,"Id":52,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":4,"Leuk":3,"Id":53,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W6D1-1","Moeilijk":5,"Leuk":5,"Id":54,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W6D2-1","Moeilijk":4,"Leuk":3,"Id":55,isChecked: true},
    {"Naam":"Evelyn","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":5,"Leuk":5,"Id":56,isChecked: true},
    {"Naam":"Aranka","Opdracht":"SCRUM","Moeilijk":1,"Leuk":1,"Id":57,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D1-1","Moeilijk":4,"Leuk":3,"Id":58,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D2-1","Moeilijk":3,"Leuk":1,"Id":59,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D2-2","Moeilijk":3,"Leuk":2,"Id":60,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D2-3","Moeilijk":4,"Leuk":1,"Id":61,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D2-4","Moeilijk":2,"Leuk":3,"Id":62,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D2-5","Moeilijk":4,"Leuk":2,"Id":63,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D3-1","Moeilijk":3,"Leuk":2,"Id":64,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D3-2","Moeilijk":2,"Leuk":1,"Id":65,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D3-4","Moeilijk":1,"Leuk":2,"Id":66,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D3-5","Moeilijk":4,"Leuk":1,"Id":67,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":2,"Leuk":3,"Id":68,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D4-1","Moeilijk":3,"Leuk":2,"Id":69,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":4,"Leuk":3,"Id":70,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W1D5 - Project - Galgje","Moeilijk":4,"Leuk":1,"Id":71,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D1-1","Moeilijk":2,"Leuk":4,"Id":72,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D1-2","Moeilijk":4,"Leuk":4,"Id":73,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D2-1","Moeilijk":3,"Leuk":4,"Id":74,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D2-2","Moeilijk":3,"Leuk":4,"Id":75,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D2-3","Moeilijk":1,"Leuk":4,"Id":76,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D3-1","Moeilijk":4,"Leuk":3,"Id":77,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D3-2","Moeilijk":4,"Leuk":1,"Id":78,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D3-3","Moeilijk":1,"Leuk":1,"Id":79,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":4,"Id":80,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D4-2","Moeilijk":2,"Leuk":3,"Id":81,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D4-3","Moeilijk":2,"Leuk":3,"Id":82,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":2,"Leuk":2,"Id":83,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D1-1","Moeilijk":4,"Leuk":2,"Id":84,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D1-2","Moeilijk":3,"Leuk":2,"Id":85,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D1-3","Moeilijk":1,"Leuk":4,"Id":86,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D1-4","Moeilijk":1,"Leuk":3,"Id":87,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D2-1","Moeilijk":1,"Leuk":3,"Id":88,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D2-2","Moeilijk":2,"Leuk":3,"Id":89,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D2-3","Moeilijk":2,"Leuk":3,"Id":90,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D3-1","Moeilijk":2,"Leuk":2,"Id":91,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D3-2","Moeilijk":4,"Leuk":3,"Id":92,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D3-3","Moeilijk":3,"Leuk":3,"Id":93,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D3-4","Moeilijk":1,"Leuk":3,"Id":94,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D4-1","Moeilijk":1,"Leuk":1,"Id":95,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D4-2","Moeilijk":3,"Leuk":2,"Id":96,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":1,"Leuk":1,"Id":97,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D2-1","Moeilijk":2,"Leuk":1,"Id":98,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D2-2","Moeilijk":3,"Leuk":2,"Id":99,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D2-3","Moeilijk":2,"Leuk":2,"Id":100,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D2-4","Moeilijk":3,"Leuk":4,"Id":101,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3-1","Moeilijk":2,"Leuk":1,"Id":102,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3-2","Moeilijk":4,"Leuk":4,"Id":103,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3-3","Moeilijk":3,"Leuk":1,"Id":104,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3-4","Moeilijk":3,"Leuk":1,"Id":105,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3-5","Moeilijk":4,"Leuk":3,"Id":106,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":4,"Leuk":4,"Id":107,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W5D4-1","Moeilijk":1,"Leuk":3,"Id":108,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":3,"Leuk":2,"Id":109,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W6D1-1","Moeilijk":1,"Leuk":1,"Id":110,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W6D2-1","Moeilijk":2,"Leuk":2,"Id":111,isChecked: true},
    {"Naam":"Aranka","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":3,"Leuk":4,"Id":112,isChecked: true},
    {"Naam":"Floris","Opdracht":"SCRUM","Moeilijk":2,"Leuk":1,"Id":113,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D1-1","Moeilijk":4,"Leuk":3,"Id":114,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D2-1","Moeilijk":1,"Leuk":2,"Id":115,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":4,"Id":116,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D2-3","Moeilijk":1,"Leuk":4,"Id":117,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D2-4","Moeilijk":3,"Leuk":4,"Id":118,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D2-5","Moeilijk":1,"Leuk":3,"Id":119,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D3-1","Moeilijk":2,"Leuk":4,"Id":120,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D3-2","Moeilijk":4,"Leuk":4,"Id":121,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D3-4","Moeilijk":4,"Leuk":2,"Id":122,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D3-5","Moeilijk":2,"Leuk":4,"Id":123,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":2,"Leuk":2,"Id":124,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D4-1","Moeilijk":1,"Leuk":3,"Id":125,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":4,"Leuk":3,"Id":126,isChecked: true},
    {"Naam":"Floris","Opdracht":"W1D5 - Project - Galgje","Moeilijk":4,"Leuk":4,"Id":127,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D1-1","Moeilijk":2,"Leuk":2,"Id":128,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D1-2","Moeilijk":4,"Leuk":1,"Id":129,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D2-1","Moeilijk":4,"Leuk":1,"Id":130,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D2-2","Moeilijk":2,"Leuk":2,"Id":131,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D2-3","Moeilijk":4,"Leuk":2,"Id":132,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D3-1","Moeilijk":1,"Leuk":1,"Id":133,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D3-2","Moeilijk":1,"Leuk":2,"Id":134,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D3-3","Moeilijk":3,"Leuk":3,"Id":135,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D4-1","Moeilijk":4,"Leuk":4,"Id":136,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D4-2","Moeilijk":3,"Leuk":1,"Id":137,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D4-3","Moeilijk":4,"Leuk":1,"Id":138,isChecked: true},
    {"Naam":"Floris","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":4,"Leuk":1,"Id":139,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D1-1","Moeilijk":4,"Leuk":3,"Id":140,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D1-2","Moeilijk":2,"Leuk":3,"Id":141,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D1-3","Moeilijk":2,"Leuk":3,"Id":142,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D1-4","Moeilijk":3,"Leuk":3,"Id":143,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D2-1","Moeilijk":3,"Leuk":2,"Id":144,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D2-2","Moeilijk":2,"Leuk":2,"Id":145,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D2-3","Moeilijk":3,"Leuk":2,"Id":146,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D3-1","Moeilijk":4,"Leuk":4,"Id":147,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D3-2","Moeilijk":2,"Leuk":4,"Id":148,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D3-3","Moeilijk":2,"Leuk":1,"Id":149,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D3-4","Moeilijk":3,"Leuk":2,"Id":150,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D4-1","Moeilijk":1,"Leuk":3,"Id":151,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D4-2","Moeilijk":2,"Leuk":2,"Id":152,isChecked: true},
    {"Naam":"Floris","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":4,"Leuk":2,"Id":153,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D2-1","Moeilijk":1,"Leuk":4,"Id":154,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D2-2","Moeilijk":2,"Leuk":3,"Id":155,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D2-3","Moeilijk":2,"Leuk":4,"Id":156,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D2-4","Moeilijk":1,"Leuk":2,"Id":157,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3-1","Moeilijk":1,"Leuk":4,"Id":158,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3-2","Moeilijk":4,"Leuk":4,"Id":159,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3-3","Moeilijk":3,"Leuk":2,"Id":160,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3-4","Moeilijk":2,"Leuk":2,"Id":161,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3-5","Moeilijk":4,"Leuk":1,"Id":162,isChecked: true},
    {"Naam":"Floris","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":2,"Leuk":2,"Id":163,isChecked: true},
    {"Naam":"Floris","Opdracht":"W5D4-1","Moeilijk":1,"Leuk":3,"Id":164,isChecked: true},
    {"Naam":"Floris","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":3,"Leuk":1,"Id":165,isChecked: true},
    {"Naam":"Floris","Opdracht":"W6D1-1","Moeilijk":3,"Leuk":2,"Id":166,isChecked: true},
    {"Naam":"Floris","Opdracht":"W6D2-1","Moeilijk":1,"Leuk":1,"Id":167,isChecked: true},
    {"Naam":"Floris","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":4,"Leuk":1,"Id":168,isChecked: true},
    {"Naam":"Hector","Opdracht":"SCRUM","Moeilijk":1,"Leuk":2,"Id":169,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D1-1","Moeilijk":1,"Leuk":4,"Id":170,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D2-1","Moeilijk":2,"Leuk":4,"Id":171,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D2-2","Moeilijk":2,"Leuk":3,"Id":172,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D2-3","Moeilijk":1,"Leuk":2,"Id":173,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D2-4","Moeilijk":1,"Leuk":3,"Id":174,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D2-5","Moeilijk":3,"Leuk":1,"Id":175,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D3-1","Moeilijk":1,"Leuk":4,"Id":176,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D3-2","Moeilijk":4,"Leuk":3,"Id":177,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D3-4","Moeilijk":3,"Leuk":1,"Id":178,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D3-5","Moeilijk":4,"Leuk":2,"Id":179,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":3,"Leuk":1,"Id":180,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D4-1","Moeilijk":1,"Leuk":1,"Id":181,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":1,"Leuk":3,"Id":182,isChecked: true},
    {"Naam":"Hector","Opdracht":"W1D5 - Project - Galgje","Moeilijk":2,"Leuk":4,"Id":183,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D1-1","Moeilijk":4,"Leuk":4,"Id":184,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D1-2","Moeilijk":3,"Leuk":2,"Id":185,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D2-1","Moeilijk":4,"Leuk":3,"Id":186,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D2-2","Moeilijk":1,"Leuk":2,"Id":187,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D2-3","Moeilijk":3,"Leuk":2,"Id":188,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D3-1","Moeilijk":3,"Leuk":1,"Id":189,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D3-2","Moeilijk":4,"Leuk":2,"Id":190,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D3-3","Moeilijk":4,"Leuk":2,"Id":191,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D4-1","Moeilijk":2,"Leuk":4,"Id":192,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D4-2","Moeilijk":4,"Leuk":1,"Id":193,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D4-3","Moeilijk":3,"Leuk":2,"Id":194,isChecked: true},
    {"Naam":"Hector","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":4,"Leuk":1,"Id":195,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D1-1","Moeilijk":1,"Leuk":1,"Id":196,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D1-2","Moeilijk":1,"Leuk":4,"Id":197,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D1-3","Moeilijk":3,"Leuk":2,"Id":198,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D1-4","Moeilijk":4,"Leuk":3,"Id":199,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D2-1","Moeilijk":1,"Leuk":3,"Id":200,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D2-2","Moeilijk":4,"Leuk":3,"Id":201,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D2-3","Moeilijk":2,"Leuk":1,"Id":202,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D3-1","Moeilijk":4,"Leuk":4,"Id":203,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D3-2","Moeilijk":3,"Leuk":1,"Id":204,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D3-3","Moeilijk":2,"Leuk":4,"Id":205,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D3-4","Moeilijk":4,"Leuk":1,"Id":206,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D4-1","Moeilijk":3,"Leuk":4,"Id":207,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D4-2","Moeilijk":1,"Leuk":4,"Id":208,isChecked: true},
    {"Naam":"Hector","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":2,"Leuk":4,"Id":209,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D2-1","Moeilijk":1,"Leuk":1,"Id":210,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D2-2","Moeilijk":2,"Leuk":1,"Id":211,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D2-3","Moeilijk":3,"Leuk":3,"Id":212,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D2-4","Moeilijk":1,"Leuk":3,"Id":213,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3-1","Moeilijk":3,"Leuk":3,"Id":214,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":4,"Id":215,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3-3","Moeilijk":3,"Leuk":1,"Id":216,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3-4","Moeilijk":1,"Leuk":3,"Id":217,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3-5","Moeilijk":1,"Leuk":2,"Id":218,isChecked: true},
    {"Naam":"Hector","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":3,"Leuk":1,"Id":219,isChecked: true},
    {"Naam":"Hector","Opdracht":"W5D4-1","Moeilijk":3,"Leuk":4,"Id":220,isChecked: true},
    {"Naam":"Hector","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":3,"Leuk":1,"Id":221,isChecked: true},
    {"Naam":"Hector","Opdracht":"W6D1-1","Moeilijk":1,"Leuk":1,"Id":222,isChecked: true},
    {"Naam":"Hector","Opdracht":"W6D2-1","Moeilijk":4,"Leuk":2,"Id":223,isChecked: true},
    {"Naam":"Hector","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":2,"Leuk":4,"Id":224,isChecked: true},
    {"Naam":"Martina","Opdracht":"SCRUM","Moeilijk":1,"Leuk":1,"Id":225,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D1-1","Moeilijk":4,"Leuk":1,"Id":226,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D2-1","Moeilijk":3,"Leuk":3,"Id":227,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D2-2","Moeilijk":2,"Leuk":1,"Id":228,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D2-3","Moeilijk":2,"Leuk":1,"Id":229,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D2-4","Moeilijk":4,"Leuk":2,"Id":230,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D2-5","Moeilijk":3,"Leuk":4,"Id":231,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D3-1","Moeilijk":3,"Leuk":4,"Id":232,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D3-2","Moeilijk":2,"Leuk":1,"Id":233,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D3-4","Moeilijk":3,"Leuk":2,"Id":234,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D3-5","Moeilijk":1,"Leuk":1,"Id":235,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":2,"Leuk":2,"Id":236,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D4-1","Moeilijk":4,"Leuk":2,"Id":237,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":1,"Leuk":3,"Id":238,isChecked: true},
    {"Naam":"Martina","Opdracht":"W1D5 - Project - Galgje","Moeilijk":1,"Leuk":4,"Id":239,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D1-1","Moeilijk":1,"Leuk":4,"Id":240,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D1-2","Moeilijk":4,"Leuk":2,"Id":241,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D2-1","Moeilijk":4,"Leuk":1,"Id":242,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D2-2","Moeilijk":3,"Leuk":3,"Id":243,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D2-3","Moeilijk":3,"Leuk":1,"Id":244,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D3-1","Moeilijk":4,"Leuk":2,"Id":245,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D3-2","Moeilijk":3,"Leuk":4,"Id":246,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D3-3","Moeilijk":3,"Leuk":3,"Id":247,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":4,"Id":248,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D4-2","Moeilijk":3,"Leuk":4,"Id":249,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D4-3","Moeilijk":3,"Leuk":4,"Id":250,isChecked: true},
    {"Naam":"Martina","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":2,"Leuk":4,"Id":251,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D1-1","Moeilijk":1,"Leuk":1,"Id":252,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D1-2","Moeilijk":3,"Leuk":3,"Id":253,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D1-3","Moeilijk":3,"Leuk":1,"Id":254,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D1-4","Moeilijk":3,"Leuk":2,"Id":255,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D2-1","Moeilijk":1,"Leuk":2,"Id":256,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D2-2","Moeilijk":2,"Leuk":4,"Id":257,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D2-3","Moeilijk":3,"Leuk":1,"Id":258,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D3-1","Moeilijk":1,"Leuk":4,"Id":259,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D3-2","Moeilijk":4,"Leuk":1,"Id":260,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D3-3","Moeilijk":3,"Leuk":3,"Id":261,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D3-4","Moeilijk":2,"Leuk":3,"Id":262,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D4-1","Moeilijk":4,"Leuk":4,"Id":263,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D4-2","Moeilijk":3,"Leuk":1,"Id":264,isChecked: true},
    {"Naam":"Martina","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":2,"Leuk":3,"Id":265,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D2-1","Moeilijk":3,"Leuk":4,"Id":266,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D2-2","Moeilijk":1,"Leuk":2,"Id":267,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D2-3","Moeilijk":3,"Leuk":4,"Id":268,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D2-4","Moeilijk":4,"Leuk":1,"Id":269,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3-1","Moeilijk":2,"Leuk":4,"Id":270,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":3,"Id":271,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3-3","Moeilijk":2,"Leuk":4,"Id":272,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3-4","Moeilijk":4,"Leuk":1,"Id":273,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3-5","Moeilijk":3,"Leuk":2,"Id":274,isChecked: true},
    {"Naam":"Martina","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":3,"Leuk":4,"Id":275,isChecked: true},
    {"Naam":"Martina","Opdracht":"W5D4-1","Moeilijk":1,"Leuk":4,"Id":276,isChecked: true},
    {"Naam":"Martina","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":1,"Leuk":1,"Id":277,isChecked: true},
    {"Naam":"Martina","Opdracht":"W6D1-1","Moeilijk":2,"Leuk":1,"Id":278,isChecked: true},
    {"Naam":"Martina","Opdracht":"W6D2-1","Moeilijk":1,"Leuk":4,"Id":279,isChecked: true},
    {"Naam":"Martina","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":1,"Leuk":4,"Id":280,isChecked: true},
    {"Naam":"Maurits","Opdracht":"SCRUM","Moeilijk":3,"Leuk":4,"Id":281,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D1-1","Moeilijk":4,"Leuk":3,"Id":282,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D2-1","Moeilijk":2,"Leuk":2,"Id":283,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":4,"Id":284,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D2-3","Moeilijk":2,"Leuk":2,"Id":285,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D2-4","Moeilijk":3,"Leuk":1,"Id":286,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D2-5","Moeilijk":2,"Leuk":3,"Id":287,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D3-1","Moeilijk":2,"Leuk":4,"Id":288,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D3-2","Moeilijk":2,"Leuk":2,"Id":289,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D3-4","Moeilijk":2,"Leuk":2,"Id":290,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D3-5","Moeilijk":1,"Leuk":3,"Id":291,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":1,"Leuk":1,"Id":292,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D4-1","Moeilijk":3,"Leuk":4,"Id":293,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":4,"Leuk":1,"Id":294,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W1D5 - Project - Galgje","Moeilijk":3,"Leuk":2,"Id":295,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D1-1","Moeilijk":1,"Leuk":1,"Id":296,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D1-2","Moeilijk":2,"Leuk":3,"Id":297,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D2-1","Moeilijk":1,"Leuk":2,"Id":298,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D2-2","Moeilijk":4,"Leuk":1,"Id":299,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D2-3","Moeilijk":2,"Leuk":2,"Id":300,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D3-1","Moeilijk":2,"Leuk":2,"Id":301,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D3-2","Moeilijk":3,"Leuk":3,"Id":302,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D3-3","Moeilijk":2,"Leuk":1,"Id":303,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":3,"Id":304,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D4-2","Moeilijk":3,"Leuk":2,"Id":305,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D4-3","Moeilijk":3,"Leuk":3,"Id":306,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":3,"Leuk":1,"Id":307,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D1-1","Moeilijk":4,"Leuk":4,"Id":308,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D1-2","Moeilijk":1,"Leuk":3,"Id":309,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D1-3","Moeilijk":1,"Leuk":4,"Id":310,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D1-4","Moeilijk":1,"Leuk":2,"Id":311,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D2-1","Moeilijk":1,"Leuk":4,"Id":312,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D2-2","Moeilijk":1,"Leuk":1,"Id":313,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D2-3","Moeilijk":4,"Leuk":3,"Id":314,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D3-1","Moeilijk":1,"Leuk":1,"Id":315,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D3-2","Moeilijk":2,"Leuk":1,"Id":316,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D3-3","Moeilijk":1,"Leuk":3,"Id":317,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D3-4","Moeilijk":4,"Leuk":1,"Id":318,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D4-1","Moeilijk":4,"Leuk":4,"Id":319,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D4-2","Moeilijk":1,"Leuk":3,"Id":320,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":3,"Leuk":4,"Id":321,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D2-1","Moeilijk":3,"Leuk":1,"Id":322,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D2-2","Moeilijk":4,"Leuk":4,"Id":323,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D2-3","Moeilijk":4,"Leuk":1,"Id":324,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D2-4","Moeilijk":2,"Leuk":3,"Id":325,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3-1","Moeilijk":3,"Leuk":1,"Id":326,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3-2","Moeilijk":3,"Leuk":2,"Id":327,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3-3","Moeilijk":3,"Leuk":4,"Id":328,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3-4","Moeilijk":1,"Leuk":3,"Id":329,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3-5","Moeilijk":2,"Leuk":1,"Id":330,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":2,"Leuk":3,"Id":331,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W5D4-1","Moeilijk":1,"Leuk":3,"Id":332,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":4,"Leuk":2,"Id":333,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W6D1-1","Moeilijk":1,"Leuk":3,"Id":334,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W6D2-1","Moeilijk":1,"Leuk":4,"Id":335,isChecked: true},
    {"Naam":"Maurits","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":3,"Leuk":3,"Id":336,isChecked: true},
    {"Naam":"Rahima","Opdracht":"SCRUM","Moeilijk":2,"Leuk":4,"Id":337,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D1-1","Moeilijk":3,"Leuk":4,"Id":338,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D2-1","Moeilijk":2,"Leuk":4,"Id":339,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":2,"Id":340,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D2-3","Moeilijk":1,"Leuk":3,"Id":341,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D2-4","Moeilijk":1,"Leuk":2,"Id":342,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D2-5","Moeilijk":1,"Leuk":3,"Id":343,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D3-1","Moeilijk":1,"Leuk":1,"Id":344,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D3-2","Moeilijk":2,"Leuk":4,"Id":345,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D3-4","Moeilijk":1,"Leuk":2,"Id":346,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D3-5","Moeilijk":2,"Leuk":2,"Id":347,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":3,"Leuk":1,"Id":348,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D4-1","Moeilijk":4,"Leuk":3,"Id":349,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":2,"Leuk":4,"Id":350,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W1D5 - Project - Galgje","Moeilijk":3,"Leuk":3,"Id":351,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D1-1","Moeilijk":2,"Leuk":2,"Id":352,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D1-2","Moeilijk":3,"Leuk":1,"Id":353,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D2-1","Moeilijk":1,"Leuk":1,"Id":354,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D2-2","Moeilijk":1,"Leuk":1,"Id":355,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D2-3","Moeilijk":4,"Leuk":2,"Id":356,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D3-1","Moeilijk":1,"Leuk":1,"Id":357,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D3-2","Moeilijk":1,"Leuk":4,"Id":358,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D3-3","Moeilijk":4,"Leuk":2,"Id":359,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D4-1","Moeilijk":4,"Leuk":4,"Id":360,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D4-2","Moeilijk":4,"Leuk":4,"Id":361,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D4-3","Moeilijk":2,"Leuk":3,"Id":362,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":3,"Leuk":1,"Id":363,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D1-1","Moeilijk":1,"Leuk":1,"Id":364,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D1-2","Moeilijk":1,"Leuk":2,"Id":365,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D1-3","Moeilijk":2,"Leuk":3,"Id":366,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D1-4","Moeilijk":2,"Leuk":4,"Id":367,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D2-1","Moeilijk":3,"Leuk":2,"Id":368,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D2-2","Moeilijk":1,"Leuk":4,"Id":369,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D2-3","Moeilijk":2,"Leuk":1,"Id":370,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D3-1","Moeilijk":3,"Leuk":1,"Id":371,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D3-2","Moeilijk":4,"Leuk":4,"Id":372,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D3-3","Moeilijk":1,"Leuk":4,"Id":373,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D3-4","Moeilijk":2,"Leuk":2,"Id":374,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D4-1","Moeilijk":1,"Leuk":2,"Id":375,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D4-2","Moeilijk":3,"Leuk":3,"Id":376,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":2,"Leuk":4,"Id":377,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D2-1","Moeilijk":2,"Leuk":4,"Id":378,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D2-2","Moeilijk":4,"Leuk":3,"Id":379,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D2-3","Moeilijk":3,"Leuk":3,"Id":380,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D2-4","Moeilijk":4,"Leuk":1,"Id":381,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3-1","Moeilijk":2,"Leuk":1,"Id":382,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":1,"Id":383,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3-3","Moeilijk":2,"Leuk":1,"Id":384,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3-4","Moeilijk":2,"Leuk":2,"Id":385,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3-5","Moeilijk":3,"Leuk":2,"Id":386,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":1,"Leuk":2,"Id":387,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W5D4-1","Moeilijk":3,"Leuk":3,"Id":388,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":2,"Leuk":3,"Id":389,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W6D1-1","Moeilijk":4,"Leuk":4,"Id":390,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W6D2-1","Moeilijk":1,"Leuk":4,"Id":391,isChecked: true},
    {"Naam":"Rahima","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":4,"Leuk":1,"Id":392,isChecked: true},
    {"Naam":"Sandra","Opdracht":"SCRUM","Moeilijk":4,"Leuk":1,"Id":393,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D1-1","Moeilijk":2,"Leuk":4,"Id":394,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D2-1","Moeilijk":3,"Leuk":4,"Id":395,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D2-2","Moeilijk":3,"Leuk":2,"Id":396,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D2-3","Moeilijk":3,"Leuk":4,"Id":397,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D2-4","Moeilijk":3,"Leuk":1,"Id":398,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D2-5","Moeilijk":4,"Leuk":3,"Id":399,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D3-1","Moeilijk":1,"Leuk":1,"Id":400,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D3-2","Moeilijk":1,"Leuk":1,"Id":401,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D3-4","Moeilijk":3,"Leuk":3,"Id":402,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D3-5","Moeilijk":4,"Leuk":3,"Id":403,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":2,"Leuk":4,"Id":404,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D4-1","Moeilijk":3,"Leuk":2,"Id":405,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":1,"Leuk":3,"Id":406,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W1D5 - Project - Galgje","Moeilijk":3,"Leuk":3,"Id":407,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D1-1","Moeilijk":4,"Leuk":1,"Id":408,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D1-2","Moeilijk":4,"Leuk":3,"Id":409,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D2-1","Moeilijk":3,"Leuk":4,"Id":410,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D2-2","Moeilijk":2,"Leuk":3,"Id":411,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D2-3","Moeilijk":4,"Leuk":3,"Id":412,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D3-1","Moeilijk":1,"Leuk":2,"Id":413,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D3-2","Moeilijk":3,"Leuk":2,"Id":414,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D3-3","Moeilijk":2,"Leuk":2,"Id":415,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":3,"Id":416,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D4-2","Moeilijk":2,"Leuk":4,"Id":417,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D4-3","Moeilijk":2,"Leuk":2,"Id":418,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":2,"Leuk":4,"Id":419,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D1-1","Moeilijk":3,"Leuk":3,"Id":420,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D1-2","Moeilijk":3,"Leuk":4,"Id":421,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D1-3","Moeilijk":2,"Leuk":4,"Id":422,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D1-4","Moeilijk":2,"Leuk":2,"Id":423,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D2-1","Moeilijk":2,"Leuk":4,"Id":424,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D2-2","Moeilijk":2,"Leuk":3,"Id":425,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D2-3","Moeilijk":1,"Leuk":2,"Id":426,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D3-1","Moeilijk":1,"Leuk":2,"Id":427,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D3-2","Moeilijk":2,"Leuk":2,"Id":428,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D3-3","Moeilijk":4,"Leuk":4,"Id":429,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D3-4","Moeilijk":3,"Leuk":2,"Id":430,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D4-1","Moeilijk":2,"Leuk":3,"Id":431,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D4-2","Moeilijk":1,"Leuk":1,"Id":432,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":1,"Leuk":2,"Id":433,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D2-1","Moeilijk":3,"Leuk":3,"Id":434,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D2-2","Moeilijk":1,"Leuk":1,"Id":435,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D2-3","Moeilijk":3,"Leuk":4,"Id":436,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D2-4","Moeilijk":1,"Leuk":4,"Id":437,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3-1","Moeilijk":3,"Leuk":1,"Id":438,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":3,"Id":439,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3-3","Moeilijk":2,"Leuk":4,"Id":440,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3-4","Moeilijk":1,"Leuk":4,"Id":441,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3-5","Moeilijk":1,"Leuk":3,"Id":442,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":3,"Leuk":4,"Id":443,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W5D4-1","Moeilijk":1,"Leuk":1,"Id":444,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":2,"Leuk":2,"Id":445,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W6D1-1","Moeilijk":1,"Leuk":4,"Id":446,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W6D2-1","Moeilijk":2,"Leuk":3,"Id":447,isChecked: true},
    {"Naam":"Sandra","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":4,"Leuk":1,"Id":448,isChecked: true},
    {"Naam":"Wietske","Opdracht":"SCRUM","Moeilijk":1,"Leuk":1,"Id":449,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D1-1","Moeilijk":4,"Leuk":3,"Id":450,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D2-1","Moeilijk":1,"Leuk":4,"Id":451,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":2,"Id":452,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D2-3","Moeilijk":2,"Leuk":3,"Id":453,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D2-4","Moeilijk":2,"Leuk":1,"Id":454,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D2-5","Moeilijk":3,"Leuk":4,"Id":455,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D3-1","Moeilijk":1,"Leuk":2,"Id":456,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D3-2","Moeilijk":1,"Leuk":4,"Id":457,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D3-4","Moeilijk":2,"Leuk":1,"Id":458,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D3-5","Moeilijk":3,"Leuk":4,"Id":459,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":2,"Leuk":4,"Id":460,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D4-1","Moeilijk":2,"Leuk":4,"Id":461,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":2,"Leuk":3,"Id":462,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W1D5 - Project - Galgje","Moeilijk":3,"Leuk":3,"Id":463,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D1-1","Moeilijk":3,"Leuk":1,"Id":464,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D1-2","Moeilijk":4,"Leuk":1,"Id":465,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D2-1","Moeilijk":2,"Leuk":2,"Id":466,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D2-2","Moeilijk":2,"Leuk":4,"Id":467,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D2-3","Moeilijk":3,"Leuk":4,"Id":468,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D3-1","Moeilijk":2,"Leuk":1,"Id":469,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D3-2","Moeilijk":1,"Leuk":1,"Id":470,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D3-3","Moeilijk":2,"Leuk":3,"Id":471,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D4-1","Moeilijk":1,"Leuk":1,"Id":472,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D4-2","Moeilijk":2,"Leuk":4,"Id":473,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D4-3","Moeilijk":4,"Leuk":3,"Id":474,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":2,"Leuk":2,"Id":475,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D1-1","Moeilijk":1,"Leuk":3,"Id":476,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D1-2","Moeilijk":4,"Leuk":4,"Id":477,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D1-3","Moeilijk":4,"Leuk":2,"Id":478,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D1-4","Moeilijk":1,"Leuk":4,"Id":479,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D2-1","Moeilijk":3,"Leuk":2,"Id":480,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D2-2","Moeilijk":1,"Leuk":3,"Id":481,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D2-3","Moeilijk":2,"Leuk":4,"Id":482,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D3-1","Moeilijk":1,"Leuk":4,"Id":483,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D3-2","Moeilijk":3,"Leuk":1,"Id":484,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D3-3","Moeilijk":1,"Leuk":3,"Id":485,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D3-4","Moeilijk":3,"Leuk":4,"Id":486,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D4-1","Moeilijk":3,"Leuk":4,"Id":487,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D4-2","Moeilijk":4,"Leuk":2,"Id":488,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":2,"Leuk":4,"Id":489,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D2-1","Moeilijk":3,"Leuk":3,"Id":490,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D2-2","Moeilijk":2,"Leuk":4,"Id":491,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D2-3","Moeilijk":1,"Leuk":2,"Id":492,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D2-4","Moeilijk":4,"Leuk":3,"Id":493,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3-1","Moeilijk":2,"Leuk":1,"Id":494,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3-2","Moeilijk":1,"Leuk":2,"Id":495,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3-3","Moeilijk":1,"Leuk":4,"Id":496,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3-4","Moeilijk":3,"Leuk":4,"Id":497,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3-5","Moeilijk":4,"Leuk":3,"Id":498,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":4,"Leuk":2,"Id":499,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W5D4-1","Moeilijk":3,"Leuk":1,"Id":500,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":4,"Leuk":2,"Id":501,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W6D1-1","Moeilijk":1,"Leuk":1,"Id":502,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W6D2-1","Moeilijk":2,"Leuk":1,"Id":503,isChecked: true},
    {"Naam":"Wietske","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":1,"Leuk":2,"Id":504,isChecked: true},
    {"Naam":"Storm","Opdracht":"SCRUM","Moeilijk":1,"Leuk":1,"Id":505,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D1-1","Moeilijk":2,"Leuk":2,"Id":506,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D2-1","Moeilijk":2,"Leuk":3,"Id":507,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D2-2","Moeilijk":1,"Leuk":3,"Id":508,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D2-3","Moeilijk":1,"Leuk":2,"Id":509,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D2-4","Moeilijk":4,"Leuk":3,"Id":510,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D2-5","Moeilijk":3,"Leuk":3,"Id":511,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D3-1","Moeilijk":2,"Leuk":3,"Id":512,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D3-2","Moeilijk":1,"Leuk":1,"Id":513,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D3-4","Moeilijk":1,"Leuk":1,"Id":514,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D3-5","Moeilijk":2,"Leuk":2,"Id":515,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D3 - Project - Guess-the-number","Moeilijk":3,"Leuk":4,"Id":516,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D4-1","Moeilijk":4,"Leuk":2,"Id":517,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D4 - Project - Kleurentoggle","Moeilijk":3,"Leuk":2,"Id":518,isChecked: true},
    {"Naam":"Storm","Opdracht":"W1D5 - Project - Galgje","Moeilijk":4,"Leuk":4,"Id":519,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D1-1","Moeilijk":2,"Leuk":4,"Id":520,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D1-2","Moeilijk":3,"Leuk":2,"Id":521,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D2-1","Moeilijk":4,"Leuk":4,"Id":522,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D2-2","Moeilijk":2,"Leuk":1,"Id":523,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D2-3","Moeilijk":1,"Leuk":1,"Id":524,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D3-1","Moeilijk":2,"Leuk":3,"Id":525,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D3-2","Moeilijk":3,"Leuk":4,"Id":526,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D3-3","Moeilijk":3,"Leuk":2,"Id":527,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D4-1","Moeilijk":3,"Leuk":4,"Id":528,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D4-2","Moeilijk":4,"Leuk":3,"Id":529,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D4-3","Moeilijk":2,"Leuk":1,"Id":530,isChecked: true},
    {"Naam":"Storm","Opdracht":"W2D5 - Project - Filmzoeker","Moeilijk":4,"Leuk":1,"Id":531,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D1-1","Moeilijk":2,"Leuk":1,"Id":532,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D1-2","Moeilijk":2,"Leuk":2,"Id":533,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D1-3","Moeilijk":1,"Leuk":2,"Id":534,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D1-4","Moeilijk":2,"Leuk":3,"Id":535,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D2-1","Moeilijk":1,"Leuk":4,"Id":536,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D2-2","Moeilijk":3,"Leuk":3,"Id":537,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D2-3","Moeilijk":3,"Leuk":4,"Id":538,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D3-1","Moeilijk":3,"Leuk":4,"Id":539,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D3-2","Moeilijk":1,"Leuk":2,"Id":540,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D3-3","Moeilijk":3,"Leuk":1,"Id":541,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D3-4","Moeilijk":3,"Leuk":1,"Id":542,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D4-1","Moeilijk":2,"Leuk":4,"Id":543,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D4-2","Moeilijk":3,"Leuk":4,"Id":544,isChecked: true},
    {"Naam":"Storm","Opdracht":"W3D5 - Project - Todo-List","Moeilijk":3,"Leuk":2,"Id":545,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D2-1","Moeilijk":2,"Leuk":1,"Id":546,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D2-2","Moeilijk":3,"Leuk":3,"Id":547,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D2-3","Moeilijk":2,"Leuk":2,"Id":548,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D2-4","Moeilijk":3,"Leuk":4,"Id":549,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3-1","Moeilijk":3,"Leuk":4,"Id":550,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3-2","Moeilijk":2,"Leuk":3,"Id":551,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3-3","Moeilijk":1,"Leuk":1,"Id":552,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3-4","Moeilijk":3,"Leuk":1,"Id":553,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3-5","Moeilijk":2,"Leuk":3,"Id":554,isChecked: true},
    {"Naam":"Storm","Opdracht":"W4D3 - Project - Next-Level CSS","Moeilijk":4,"Leuk":1,"Id":555,isChecked: true},
    {"Naam":"Storm","Opdracht":"W5D4-1","Moeilijk":2,"Leuk":2,"Id":556,isChecked: true},
    {"Naam":"Storm","Opdracht":"W5D5 - Project - Lil_Playlist","Moeilijk":1,"Leuk":2,"Id":557,isChecked: true},
    {"Naam":"Storm","Opdracht":"W6D1-1","Moeilijk":4,"Leuk":4,"Id":558,isChecked: true},
    {"Naam":"Storm","Opdracht":"W6D2-1","Moeilijk":1,"Leuk":1,"Id":559,isChecked: true},
    {"Naam":"Storm","Opdracht":"W6D2 - Project - Eindopdracht","Moeilijk":3,"Leuk":3,"Id":560,isChecked: true},
];


           
      export default students    
        